"""gender column

Revision ID: 2abf02e084fb
Revises: 6f0062243e0e
Create Date: 2023-06-01 23:19:02.214556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2abf02e084fb'
down_revision = '6f0062243e0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('gender', sa.Enum('male', 'female'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'gender')
    # ### end Alembic commands ###
