"""sire and dam

Revision ID: 6f0062243e0e
Revises: d89263b05479
Create Date: 2023-06-01 22:58:34.633733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0062243e0e'
down_revision = 'd89263b05479'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('sire', sa.Integer(), nullable=True))
    op.add_column('records', sa.Column('dam', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'records', 'records', ['sire'], ['id'])
    op.create_foreign_key(None, 'records', 'records', ['dam'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.drop_column('records', 'dam')
    op.drop_column('records', 'sire')
    # ### end Alembic commands ###
