"""varchar to text

Revision ID: a53148a0e394
Revises: 618c95d0af55
Create Date: 2023-06-29 16:19:33.148144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53148a0e394'
down_revision = '618c95d0af55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
