"""weight column

Revision ID: d4ca76af93bb
Revises: 2abf02e084fb
Create Date: 2023-06-13 15:45:30.679244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4ca76af93bb'
down_revision = '2abf02e084fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'weight')
    # ### end Alembic commands ###
