"""setting up records table

Revision ID: d89263b05479
Revises: 
Create Date: 2023-05-28 15:00:53.893831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd89263b05479'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('tag_colour', sa.String(length=255), nullable=True),
    sa.Column('number_of_kids', sa.Integer(), nullable=True),
    sa.Column('colour', sa.Integer(), nullable=True),
    sa.Column('castrated', sa.Boolean(), nullable=True),
    sa.Column('health_condition', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_id'), 'records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_records_id'), table_name='records')
    op.drop_table('records')
    # ### end Alembic commands ###
